import streamlit as st
import pandas as pd
from pathlib import Path


# ============================================================
# COEN542 HOUSEHOLD ENERGY ANALYTICS DASHBOARD
# ============================================================

# app.py is inside:
# C:\Users\User\Documents\coen542 project\app\dashboard
#
# results is inside:
# C:\Users\User\Documents\coen542 project\app\results

BASE_DIR = Path(__file__).resolve().parent.parent
RESULTS_DIR = BASE_DIR / "results"


# ============================================================
# PAGE CONFIGURATION
# ============================================================

st.set_page_config(
    page_title="COEN542 Energy Analytics",
    page_icon="⚡",
    layout="wide",
    initial_sidebar_state="expanded",
)


# ============================================================
# STYLING
# ============================================================

st.markdown(
    """
    <style>
        .main-title {
            font-size: 2.2rem;
            font-weight: 700;
        }

        .section-title {
            font-size: 1.4rem;
            font-weight: 600;
        }
    </style>
    """,
    unsafe_allow_html=True,
)


# ============================================================
# RESULT LOADING
# ============================================================

def _read_csv_files(files):
    """Read and combine one or more CSV files."""

    frames = []

    for file in sorted(files):
        try:
            frames.append(pd.read_csv(file))
        except Exception as exc:
            st.warning(
                f"Could not read {file.name}: {exc}"
            )

    if not frames:
        return None

    return pd.concat(
        frames,
        ignore_index=True
    )


@st.cache_data(show_spinner=False)
def load_spark_result(result_name):
    """
    Load a Spark result.

    Spark normally produces:

        result_name/
            part-00000-....csv
            _SUCCESS

    Ordinary CSV files are also supported.
    """

    result_path = RESULTS_DIR / result_name

    if not result_path.exists():
        return None

    # Spark output directory
    if result_path.is_dir():

        part_files = sorted(
            result_path.glob("part-*.csv")
        )

        if part_files:
            return _read_csv_files(
                part_files
            )

        csv_files = sorted(
            result_path.glob("*.csv")
        )

        if csv_files:
            return _read_csv_files(
                csv_files
            )

        return None

    # Direct CSV
    if (
        result_path.is_file()
        and result_path.suffix.lower() == ".csv"
    ):
        return _read_csv_files(
            [result_path]
        )

    return None


# ============================================================
# LOAD SPARK RESULTS
# ============================================================

overall = load_spark_result(
    "overall_statistics"
)

hourly = load_spark_result(
    "hourly_consumption"
)

daily = load_spark_result(
    "daily_consumption"
)

monthly = load_spark_result(
    "monthly_consumption"
)

household = load_spark_result(
    "household_consumption"
)

weekday = load_spark_result(
    "weekday_consumption"
)

peak_hour = load_spark_result(
    "peak_hour"
)

peak_day = load_spark_result(
    "peak_day"
)

peak_month = load_spark_result(
    "peak_month"
)


# ============================================================
# ANOMALY RESULTS
# ============================================================
# ============================================================
# ANOMALY RESULTS
# ============================================================

# These names must match the directories actually
# generated by spark_processing.py.

anomaly_summary = load_spark_result(
    "anomaly_summary"
)

consumption_anomalies = load_spark_result(
    "anomaly_detection"
)

# The current Spark script does not save a separate
# household_anomalies result. Therefore, derive the
# household anomaly analysis directly from the saved
# anomaly_detection result.

household_anomalies = None

if (
    consumption_anomalies is not None
    and not consumption_anomalies.empty
    and "LCLid" in consumption_anomalies.columns
):
    household_anomalies = (
        consumption_anomalies
        .groupby("LCLid")
        .agg(
            anomaly_count=("LCLid", "size"),
            anomalous_energy_kwh=("energy_kwh", "sum"),
            maximum_anomalous_kwh=("energy_kwh", "max"),
        )
        .reset_index()
        .sort_values(
            "anomaly_count",
            ascending=False
        )
    )

# ============================================================
# SCALABILITY RESULT
# ============================================================

scalability = load_spark_result(
    "scalability_experiment/scalability_results.csv"
)


# ============================================================
# HELPERS
# ============================================================

def number(value):
    """Format numeric values."""

    try:
        return f"{float(value):,.2f}"
    except Exception:
        return "0.00"


def first_value(
    dataframe,
    column,
    default=None
):
    """Safely retrieve first value."""

    if (
        dataframe is None
        or dataframe.empty
        or column not in dataframe.columns
    ):
        return default

    value = dataframe[column].iloc[0]

    if pd.isna(value):
        return default

    return value


def result_status(dataframe):
    """Return result availability."""

    if (
        dataframe is not None
        and not dataframe.empty
    ):
        return "Available"

    return "Not found"


# ============================================================
# HEADER
# ============================================================

st.markdown(
    '<div class="main-title">'
    '⚡ Household Energy Analytics Dashboard'
    '</div>',
    unsafe_allow_html=True,
)

st.markdown(
    """
    **COEN542 — End-to-End Big Data Analytics System**

    Energy Dataset → **Apache Kafka** → **MongoDB**
    → **Apache Spark/PySpark** → Analytics
    → **Interactive Dashboard**
    """
)

st.markdown("---")


# ============================================================
# SIDEBAR
# ============================================================

st.sidebar.title("Navigation")

page = st.sidebar.radio(
    "Select Analysis",
    [
        "Overview",
        "Hourly Consumption",
        "Daily Consumption",
        "Monthly Consumption",
        "Household Analysis",
        "Weekday Analysis",
        "Anomaly Detection",
        "Scalability Experiment",
    ],
)


# ============================================================
# PIPELINE
# ============================================================

st.sidebar.markdown("---")

st.sidebar.subheader(
    "Big Data Pipeline"
)

st.sidebar.write(
    "📄 Energy Dataset"
)

st.sidebar.write("↓")

st.sidebar.write(
    "📨 Apache Kafka"
)

st.sidebar.write("↓")

st.sidebar.write(
    "🍃 MongoDB"
)

st.sidebar.write("↓")

st.sidebar.write(
    "⚡ Apache Spark"
)

st.sidebar.write("↓")

st.sidebar.write(
    "📊 Analytics"
)

st.sidebar.write("↓")

st.sidebar.write(
    "📈 Streamlit Dashboard"
)


# ============================================================
# RESULT STATUS
# ============================================================

st.sidebar.markdown("---")

st.sidebar.subheader(
    "Analytics Status"
)

st.sidebar.write(
    f"Overall: **{result_status(overall)}**"
)

st.sidebar.write(
    f"Hourly: **{result_status(hourly)}**"
)

st.sidebar.write(
    f"Daily: **{result_status(daily)}**"
)

st.sidebar.write(
    f"Monthly: **{result_status(monthly)}**"
)

st.sidebar.write(
    f"Household: **{result_status(household)}**"
)

st.sidebar.write(
    f"Anomaly Analysis: **{result_status(anomaly_summary)}**"
)

st.sidebar.write(
    f"Scalability: **{result_status(scalability)}**"
)

st.sidebar.markdown("---")

st.sidebar.caption(
    f"Results directory:\n{RESULTS_DIR}"
)


# ============================================================
# OVERVIEW
# ============================================================

if page == "Overview":

    st.header(
        "Energy Consumption Overview"
    )

    if (
        overall is None
        or overall.empty
    ):

        st.error(
            "Overall statistics could not be loaded."
        )

        st.code(
            str(
                RESULTS_DIR
                / "overall_statistics"
            )
        )

        st.stop()

    total_energy = first_value(
        overall,
        "total_energy_kwh",
        0,
    )

    average_energy = first_value(
        overall,
        "average_half_hour_kwh",
        0,
    )

    minimum_energy = first_value(
        overall,
        "minimum_half_hour_kwh",
        0,
    )

    maximum_energy = first_value(
        overall,
        "maximum_half_hour_kwh",
        0,
    )

    # --------------------------------------------------------
    # KPI CARDS
    # --------------------------------------------------------

    c1, c2, c3, c4 = st.columns(4)

    c1.metric(
        "Total Energy",
        f"{number(total_energy)} kWh",
    )

    c2.metric(
        "Average / Half-hour",
        f"{number(average_energy)} kWh",
    )

    c3.metric(
        "Minimum / Half-hour",
        f"{number(minimum_energy)} kWh",
    )

    c4.metric(
        "Maximum / Half-hour",
        f"{number(maximum_energy)} kWh",
    )

    st.markdown("---")

    # --------------------------------------------------------
    # PEAK INFORMATION
    # --------------------------------------------------------

    st.subheader(
        "Peak Consumption"
    )

    p1, p2, p3 = st.columns(3)

    if (
        peak_hour is not None
        and not peak_hour.empty
    ):

        hour = first_value(
            peak_hour,
            "hour",
            0,
        )

        energy = first_value(
            peak_hour,
            "total_energy_kwh",
            0,
        )

        p1.metric(
            "Peak Hour",
            f"{int(hour):02d}:00",
            f"{number(energy)} kWh",
        )

    if (
        peak_day is not None
        and not peak_day.empty
    ):

        date = first_value(
            peak_day,
            "date",
            "N/A",
        )

        energy = first_value(
            peak_day,
            "total_energy_kwh",
            0,
        )

        p2.metric(
            "Peak Day",
            str(date),
            f"{number(energy)} kWh",
        )

    if (
        peak_month is not None
        and not peak_month.empty
    ):

        year_value = first_value(
            peak_month,
            "year",
            0,
        )

        month_value = first_value(
            peak_month,
            "month",
            0,
        )

        energy = first_value(
            peak_month,
            "total_energy_kwh",
            0,
        )

        p3.metric(
            "Peak Month",
            f"{int(year_value)}-{int(month_value):02d}",
            f"{number(energy)} kWh",
        )

    st.markdown("---")

    # --------------------------------------------------------
    # HOURLY PATTERN
    # --------------------------------------------------------

    st.subheader(
        "Hourly Consumption Pattern"
    )

    if (
        hourly is not None
        and not hourly.empty
    ):

        chart = hourly.copy()

        chart["hour"] = pd.to_numeric(
            chart["hour"],
            errors="coerce",
        )

        chart["total_energy_kwh"] = pd.to_numeric(
            chart["total_energy_kwh"],
            errors="coerce",
        )

        chart = chart.dropna(
            subset=[
                "hour",
                "total_energy_kwh",
            ]
        )

        chart = chart.sort_values(
            "hour"
        )

        st.line_chart(
            chart.set_index("hour")[
                "total_energy_kwh"
            ]
        )

    # --------------------------------------------------------
    # PIPELINE
    # --------------------------------------------------------

    st.markdown("---")

    st.subheader(
        "System Architecture"
    )

    st.code(
        """
Energy Dataset
      ↓
Apache Kafka
      ↓
MongoDB
      ↓
Apache Spark / PySpark
      ↓
Data Cleaning & Feature Engineering
      ↓
Energy Analytics
      ↓
Streamlit Dashboard
        """,
        language="text",
    )


# ============================================================
# HOURLY
# ============================================================

elif page == "Hourly Consumption":

    st.header(
        "Hourly Energy Consumption"
    )

    if hourly is None or hourly.empty:

        st.warning(
            "Hourly results were not found."
        )

        st.stop()

    data = hourly.copy()

    data["hour"] = pd.to_numeric(
        data["hour"],
        errors="coerce",
    )

    data["total_energy_kwh"] = pd.to_numeric(
        data["total_energy_kwh"],
        errors="coerce",
    )

    data = data.dropna(
        subset=[
            "hour",
            "total_energy_kwh",
        ]
    )

    data = data.sort_values(
        "hour"
    )

    st.subheader(
        "Consumption by Hour"
    )

    st.line_chart(
        data.set_index("hour")[
            "total_energy_kwh"
        ]
    )

    peak = data.loc[
        data["total_energy_kwh"].idxmax()
    ]

    c1, c2 = st.columns(2)

    c1.metric(
        "Highest Consumption Hour",
        f"{int(peak['hour']):02d}:00",
    )

    c2.metric(
        "Consumption",
        f"{number(peak['total_energy_kwh'])} kWh",
    )

    st.subheader(
        "Hourly Data"
    )

    st.dataframe(
        data,
        use_container_width=True,
        hide_index=True,
    )


# ============================================================
# DAILY
# ============================================================

elif page == "Daily Consumption":

    st.header(
        "Daily Energy Consumption"
    )

    if daily is None or daily.empty:

        st.warning(
            "Daily results were not found."
        )

        st.stop()

    data = daily.copy()

    data["date"] = pd.to_datetime(
        data["date"],
        errors="coerce",
    )

    data["total_energy_kwh"] = pd.to_numeric(
        data["total_energy_kwh"],
        errors="coerce",
    )

    data = data.dropna(
        subset=[
            "date",
            "total_energy_kwh",
        ]
    )

    data = data.sort_values(
        "date"
    )

    st.subheader(
        "Daily Consumption Trend"
    )

    st.line_chart(
        data.set_index("date")[
            "total_energy_kwh"
        ]
    )

    peak = data.loc[
        data["total_energy_kwh"].idxmax()
    ]

    c1, c2 = st.columns(2)

    c1.metric(
        "Peak Consumption Day",
        peak["date"].strftime(
            "%Y-%m-%d"
        ),
    )

    c2.metric(
        "Peak Daily Consumption",
        f"{number(peak['total_energy_kwh'])} kWh",
    )

    st.subheader(
        "Daily Data"
    )

    st.dataframe(
        data,
        use_container_width=True,
        hide_index=True,
    )


# ============================================================
# MONTHLY
# ============================================================

elif page == "Monthly Consumption":

    st.header(
        "Monthly Energy Consumption"
    )

    if monthly is None or monthly.empty:

        st.warning(
            "Monthly results were not found."
        )

        st.stop()

    data = monthly.copy()

    data["year"] = pd.to_numeric(
        data["year"],
        errors="coerce",
    )

    data["month"] = pd.to_numeric(
        data["month"],
        errors="coerce",
    )

    data["total_energy_kwh"] = pd.to_numeric(
        data["total_energy_kwh"],
        errors="coerce",
    )

    data = data.dropna(
        subset=[
            "year",
            "month",
            "total_energy_kwh",
        ]
    )

    data["year"] = data[
        "year"
    ].astype(int)

    data["month"] = data[
        "month"
    ].astype(int)

    data["period"] = (
        data["year"].astype(str)
        + "-"
        + data["month"]
        .astype(str)
        .str.zfill(2)
    )

    data = data.sort_values(
        [
            "year",
            "month",
        ]
    )

    st.subheader(
        "Monthly Consumption"
    )

    st.bar_chart(
        data.set_index("period")[
            "total_energy_kwh"
        ]
    )

    peak = data.loc[
        data["total_energy_kwh"].idxmax()
    ]

    c1, c2 = st.columns(2)

    c1.metric(
        "Peak Consumption Month",
        peak["period"],
    )

    c2.metric(
        "Peak Monthly Consumption",
        f"{number(peak['total_energy_kwh'])} kWh",
    )

    st.subheader(
        "Monthly Data"
    )

    st.dataframe(
        data,
        use_container_width=True,
        hide_index=True,
    )


# ============================================================
# HOUSEHOLD ANALYSIS
# ============================================================

elif page == "Household Analysis":

    st.header(
        "Household Energy Analysis"
    )

    if household is None or household.empty:

        st.warning(
            "Household results were not found."
        )

        st.stop()

    data = household.copy()

    if "LCLid" not in data.columns:

        st.dataframe(
            data,
            use_container_width=True,
            hide_index=True,
        )

        st.stop()

    households = sorted(
        data["LCLid"]
        .dropna()
        .astype(str)
        .unique()
    )

    selected = st.selectbox(
        "Select Household",
        households,
    )

    selected_data = data[
        data["LCLid"].astype(str)
        == selected
    ].copy()

    st.subheader(
        f"Consumption for {selected}"
    )

    if (
        "total_energy_kwh"
        in selected_data.columns
    ):

        selected_data[
            "total_energy_kwh"
        ] = pd.to_numeric(
            selected_data[
                "total_energy_kwh"
            ],
            errors="coerce",
        )

        total = selected_data[
            "total_energy_kwh"
        ].sum()

        st.metric(
            "Total Household Consumption",
            f"{number(total)} kWh",
        )

    st.dataframe(
        selected_data,
        use_container_width=True,
        hide_index=True,
    )


# ============================================================
# WEEKDAY ANALYSIS
# ============================================================

elif page == "Weekday Analysis":

    st.header(
        "Energy Consumption by Day of Week"
    )

    if weekday is None or weekday.empty:

        st.warning(
            "Weekday results were not found."
        )

        st.stop()

    data = weekday.copy()

    if (
        "total_energy_kwh"
        in data.columns
    ):

        data[
            "total_energy_kwh"
        ] = pd.to_numeric(
            data[
                "total_energy_kwh"
            ],
            errors="coerce",
        )

    if (
        "day_of_week"
        in data.columns
        and
        "total_energy_kwh"
        in data.columns
    ):

        chart = data[
            [
                "day_of_week",
                "total_energy_kwh",
            ]
        ].dropna()

        st.bar_chart(
            chart.set_index(
                "day_of_week"
            )[
                "total_energy_kwh"
            ]
        )

    st.dataframe(
        data,
        use_container_width=True,
        hide_index=True,
    )


# ============================================================
# ANOMALY DETECTION
# ============================================================

elif page == "Anomaly Detection":

    st.header(
        "⚠️ Energy Consumption Anomaly Detection"
    )

    st.markdown(
        """
        Anomalies are detected using the **Interquartile Range
        (IQR) statistical method** implemented with Apache Spark.

        A record is treated as anomalous when its energy
        consumption falls outside the calculated IQR thresholds.
        """
    )

    # --------------------------------------------------------
    # CHECK SUMMARY
    # --------------------------------------------------------

    if (
        anomaly_summary is None
        or anomaly_summary.empty
    ):

        st.error(
            "Anomaly summary was not found."
        )

        st.info(
            "Run spark_processing.py again."
        )

        st.stop()

    # --------------------------------------------------------
    # READ SUMMARY
    # --------------------------------------------------------

    q1 = first_value(
        anomaly_summary,
        "q1_kwh",
        0,
    )

    q3 = first_value(
        anomaly_summary,
        "q3_kwh",
        0,
    )

    iqr = first_value(
        anomaly_summary,
        "iqr_kwh",
        0,
    )

    lower_threshold = first_value(
        anomaly_summary,
        "lower_threshold_kwh",
        0,
    )

    upper_threshold = first_value(
        anomaly_summary,
        "upper_threshold_kwh",
        0,
    )

    total_clean_records = first_value(
        anomaly_summary,
        "total_clean_records",
        0,
    )

    anomaly_records = first_value(
        anomaly_summary,
        "anomaly_records",
        0,
    )

    anomaly_percentage = first_value(
        anomaly_summary,
        "anomaly_percentage",
        0,
    )

    # --------------------------------------------------------
    # KPI CARDS
    # --------------------------------------------------------

    st.subheader(
        "Anomaly Summary"
    )

    a1, a2, a3, a4 = st.columns(4)

    a1.metric(
        "Clean Records",
        f"{int(total_clean_records):,}",
    )

    a2.metric(
        "Anomalous Records",
        f"{int(anomaly_records):,}",
    )

    a3.metric(
        "Anomaly Rate",
        f"{float(anomaly_percentage):.4f}%",
    )

    a4.metric(
        "Upper Threshold",
        f"{number(upper_threshold)} kWh",
    )

    st.markdown("---")

    # --------------------------------------------------------
    # IQR STATISTICS
    # --------------------------------------------------------

    st.subheader(
        "IQR Statistical Thresholds"
    )

    t1, t2, t3, t4 = st.columns(4)

    t1.metric(
        "Q1",
        f"{number(q1)} kWh",
    )

    t2.metric(
        "Q3",
        f"{number(q3)} kWh",
    )

    t3.metric(
        "IQR",
        f"{number(iqr)} kWh",
    )

    t4.metric(
        "Lower Threshold",
        f"{number(lower_threshold)} kWh",
    )

    st.markdown("---")

    # --------------------------------------------------------
    # ANOMALY RECORDS
    # --------------------------------------------------------

    st.subheader(
        "Detected Anomalous Consumption Records"
    )

    if (
        consumption_anomalies is not None
        and not consumption_anomalies.empty
    ):

        anomaly_data = (
            consumption_anomalies.copy()
        )

        if "energy_kwh" in anomaly_data.columns:

            anomaly_data[
                "energy_kwh"
            ] = pd.to_numeric(
                anomaly_data[
                    "energy_kwh"
                ],
                errors="coerce",
            )

        st.dataframe(
            anomaly_data,
            use_container_width=True,
            hide_index=True,
        )

    else:

        st.info(
            "No anomalous consumption records were found."
        )

    st.markdown("---")

    # --------------------------------------------------------
    # HOUSEHOLDS WITH MOST ANOMALIES
    # --------------------------------------------------------

    st.subheader(
        "Households with Most Anomalies"
    )

    if (
        household_anomalies is not None
        and not household_anomalies.empty
    ):

        household_data = (
            household_anomalies.copy()
        )

        if "anomaly_count" in household_data.columns:

            household_data[
                "anomaly_count"
            ] = pd.to_numeric(
                household_data[
                    "anomaly_count"
                ],
                errors="coerce",
            )

        if (
            "LCLid"
            in household_data.columns
            and
            "anomaly_count"
            in household_data.columns
        ):

            chart = (
                household_data
                .head(10)
                .set_index("LCLid")[
                    "anomaly_count"
                ]
            )

            st.bar_chart(
                chart
            )

        st.dataframe(
            household_data,
            use_container_width=True,
            hide_index=True,
        )

    else:

        st.info(
            "Household anomaly results were not found."
        )

    st.markdown("---")

    # --------------------------------------------------------
    # ANALYTICAL INTERPRETATION
    # --------------------------------------------------------

    st.subheader(
        "Analytical Interpretation"
    )

    st.write(
        f"""
        The Spark-based IQR analysis evaluated
        **{int(total_clean_records):,} cleaned energy records**.

        The calculated interquartile range is
        **{number(iqr)} kWh**, with an upper anomaly threshold
        of **{number(upper_threshold)} kWh**.

        The analysis identified
        **{int(anomaly_records):,} anomalous records**, representing
        approximately **{float(anomaly_percentage):.4f}%** of the
        cleaned dataset.

        These records represent unusual consumption observations
        according to the statistical IQR criterion. They can be
        investigated further as possible abnormal consumption
        events, measurement irregularities, or unusually high/low
        energy usage.
        """
    )


# ============================================================
# SCALABILITY EXPERIMENT
# ============================================================

elif page == "Scalability Experiment":

    st.header(
        "📈 Mandatory Scalability Experiment"
    )

    st.markdown(
        """
        The scalability experiment evaluates the Spark processing
        workload at **25%, 50%, and 100%** of the available dataset.

        Three runs were performed for each data size after a Spark
        warm-up, and the median execution time was used.
        """
    )

    if (
        scalability is None
        or scalability.empty
    ):

        st.error(
            "Scalability results were not found."
        )

        st.code(
            str(
                RESULTS_DIR
                / "scalability_experiment"
                / "scalability_results.csv"
            )
        )

        st.stop()

    data = scalability.copy()

    st.subheader(
        "Scalability Results"
    )

    st.dataframe(
        data,
        use_container_width=True,
        hide_index=True,
    )

    # --------------------------------------------------------
    # IDENTIFY COLUMNS
    # --------------------------------------------------------

    size_column = next(
        (
            c
            for c in data.columns
            if "size" in c.lower()
        ),
        None,
    )

    time_column = next(
        (
            c
            for c in data.columns
            if "time" in c.lower()
        ),
        None,
    )

    throughput_column = next(
        (
            c
            for c in data.columns
            if "throughput"
            in c.lower()
        ),
        None,
    )

    # --------------------------------------------------------
    # EXECUTION TIME
    # --------------------------------------------------------

    if (
        size_column
        and time_column
    ):

        st.subheader(
            "Execution Time vs Data Size"
        )

        execution = data[
            [
                size_column,
                time_column,
            ]
        ].copy()

        execution[
            time_column
        ] = pd.to_numeric(
            execution[
                time_column
            ],
            errors="coerce",
        )

        st.line_chart(
            execution.set_index(
                size_column
            )[
                time_column
            ]
        )

    # --------------------------------------------------------
    # THROUGHPUT
    # --------------------------------------------------------

    if (
        size_column
        and throughput_column
    ):

        st.subheader(
            "Processing Throughput vs Data Size"
        )

        throughput = data[
            [
                size_column,
                throughput_column,
            ]
        ].copy()

        throughput[
            throughput_column
        ] = pd.to_numeric(
            throughput[
                throughput_column
            ],
            errors="coerce",
        )

        st.line_chart(
            throughput.set_index(
                size_column
            )[
                throughput_column
            ]
        )

    st.info(
        """
        These measurements represent the performance observed
        on the local Spark environment used for this project.
        They demonstrate how the implemented processing pipeline
        behaves as the amount of data increases.
        """
    )


# ============================================================
# FOOTER
# ============================================================

st.markdown("---")

st.caption(
    "COEN542 Household Energy Analytics | "
    "Kafka → MongoDB → PySpark → Analytics → Streamlit"
)